"""Add B2B LDAP organization models

Revision ID: 6c5e90488a6f
Revises: 05c7dd10775a
Create Date: 2026-02-23 17:01:37.304785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6c5e90488a6f'
down_revision: Union[str, None] = '05c7dd10775a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('fiscal_id', sa.String(length=50), nullable=True),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_is_deleted'), 'companies', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_tenant_id'), 'companies', ['tenant_id'], unique=False)
    op.create_table('company_divisions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_divisions_company_id'), 'company_divisions', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_divisions_is_deleted'), 'company_divisions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_company_divisions_tenant_id'), 'company_divisions', ['tenant_id'], unique=False)
    op.add_column('users', sa.Column('division_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_users_division_id'), 'users', ['division_id'], unique=False)
    op.create_foreign_key(None, 'users', 'company_divisions', ['division_id'], ['id'])
    op.drop_column('users', 'company_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('company_name', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_division_id'), table_name='users')
    op.drop_column('users', 'division_id')
    op.drop_index(op.f('ix_company_divisions_tenant_id'), table_name='company_divisions')
    op.drop_index(op.f('ix_company_divisions_is_deleted'), table_name='company_divisions')
    op.drop_index(op.f('ix_company_divisions_company_id'), table_name='company_divisions')
    op.drop_table('company_divisions')
    op.drop_index(op.f('ix_companies_tenant_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_is_deleted'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
