"""Add CRM External IDs to entities

Revision ID: b5e856731487
Revises: 6c5e90488a6f
Create Date: 2026-02-23 17:14:46.923008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5e856731487'
down_revision: Union[str, None] = '6c5e90488a6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('crm_company_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_companies_crm_company_id'), 'companies', ['crm_company_id'], unique=False)
    op.add_column('company_divisions', sa.Column('crm_division_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_company_divisions_crm_division_id'), 'company_divisions', ['crm_division_id'], unique=False)
    op.add_column('users', sa.Column('crm_contact_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_crm_contact_id'), 'users', ['crm_contact_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_crm_contact_id'), table_name='users')
    op.drop_column('users', 'crm_contact_id')
    op.drop_index(op.f('ix_company_divisions_crm_division_id'), table_name='company_divisions')
    op.drop_column('company_divisions', 'crm_division_id')
    op.drop_index(op.f('ix_companies_crm_company_id'), table_name='companies')
    op.drop_column('companies', 'crm_company_id')
    # ### end Alembic commands ###
