"""add_advisors_table

Revision ID: ef394856ba49
Revises: f46f86cf0c69
Create Date: 2026-03-10 17:30:13.737639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef394856ba49'
down_revision: Union[str, None] = 'f46f86cf0c69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advisors',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('telegram_user_id', sa.String(length=100), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advisors_is_available'), 'advisors', ['is_available'], unique=False)
    op.create_index(op.f('ix_advisors_tenant_id'), 'advisors', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_advisors_tenant_id'), table_name='advisors')
    op.drop_index(op.f('ix_advisors_is_available'), table_name='advisors')
    op.drop_table('advisors')
    # ### end Alembic commands ###
