"""Add missing foreign keys

Revision ID: f46f86cf0c69
Revises: b5e856731487
Create Date: 2026-02-23 19:56:14.978323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f46f86cf0c69'
down_revision: Union[str, None] = 'b5e856731487'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'conversations', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'leads_opportunities', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'])
    op.create_foreign_key(None, 'opportunity_product_recommendations', 'leads_opportunities', ['opportunity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'opportunity_product_recommendations', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'leads_opportunities', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    # ### end Alembic commands ###
