from pydantic import BaseModel, Field
from typing import Optional, Dict, Any
from datetime import datetime

class IncomingMessage(BaseModel):
    """
    Unified schema for all incoming messages regardless of the platform (WhatsApp, Telegram, Web).
    Producers must map their specific webhook payload to this standard format.
    """
    platform: str = Field(..., description="The source platform: 'telegram', 'whatsapp', 'web'")
    platform_user_id: str = Field(..., description="The unique ID of the user in that platform (e.g. phone number or chat ID)")
    tenant_id: str = Field(..., description="The ID of the SaaS tenant receiving this message")
    
    content: str = Field(..., description="The actual text message sent by the user")
    
    # Optional metadata extracted from the webhook
    user_name: Optional[str] = Field(default=None, description="The display name of the user if provided by the platform")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Any additional platform-specific payload data")
    
    timestamp: datetime = Field(default_factory=datetime.utcnow)

class AgentResponse(BaseModel):
    """
    Standard format for the Agent's response before it is formatted by the specific producer for delivery.
    """
    recipient_id: str = Field(..., description="The platform_user_id to send the response back to")
    content: str = Field(..., description="The text response generated by the LLM")
    
    # Allows the system to know if this response closes a ticket, etc.
    action_type: str = Field(default="message", description="'message', 'handoff', 'close'")
